const TIME_STRING_LENGTH = 5;

const DATE_TIME_LENGTH = 16;

const MILLISECONDS_IN_MINUTE = 60000;

const MINUTES_IN_HOUR = 60;

const HOURS_IN_DAY = 24;

export {TIME_STRING_LENGTH, DATE_TIME_LENGTH, MILLISECONDS_IN_MINUTE, MINUTES_IN_HOUR, HOURS_IN_DAY};
